version: '3.5'
services:
  app: 
    image: jjpro/tanks:latest
    # build:
    #   context: .
    restart: unless-stopped
    ports: 
      - "4000:4000"
    environment:
      - PHX_HOST=localhost # change this to your domain or IP of deployment
      - POSTGRES_HOST=db
    env_file:
      - .env
    depends_on: 
      - db
  
  db: 
    image: postgres:14.4-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: